import { saveIntegration, addAuditLog, getProposal, getOptions } from '../database.js';
import { Integration } from '../../types.js';

export async function createGitHubIssue(proposalId: string, summaryText?: string): Promise<Integration> {
  const stepName = 'GitHub Agent';
  addAuditLog(proposalId, stepName, 'Task Dispatch Initiated', 'Assembling architectural issue payload from human approved document.');

  const proposal = getProposal(proposalId);
  const options = getOptions(proposalId);
  const selectedOption = options.find(o => o.id === proposal?.selectedOptionId);

  const issueTitle = `ARIA Architecture Delivery - ${selectedOption?.title || 'System Implementation'}`;
  
  const issueBody = `
# ARIA Generated Delivery Task

## Summary
${summaryText || 'This task represents the core development work required to implement the approved Solution Architect design.'}

## Recommended Option
${selectedOption?.title || 'Selected Design Pattern'}

## Key Controls
- **RBAC:** Multi-tier role-based access control.
- **Least Privilege:** Cloud IAM microservice identities limit blast radius.
- **Data Minimisation:** Fields truncated before writing to transaction ledger.
- **Sensitive Data Masking:** Column-level encryption via KMS keys.
- **Human Approval:** Deployment and key operations gated by explicit security reviews.
- **Audit Trail:** Immutable application logs for forensic tracking.
- **Prompt Injection Protection:** Boundaries sanitised via regex and strict schema validations.
- **Monitoring and Fallback:** Real-time health metrics triggering replica VM fallbacks.

## Next Steps
- Validate requirements and perform a walkthrough with stakeholders.
- Review architecture specifications and Terraform scripts.
- Confirm security compliance and verify network access controls.
- Build POC using the recommended tech stack.
- Review governance checklist alignments.
- Prepare Confluence shortlist document.

## ARIA Audit
Generated by ARIA after explicit human approval.
Proposal Reference: ${proposalId}
Technical Audit Score: ${proposal?.finalScore || 'N/A'}/100
Governance Status: ${proposal?.finalGovernance || 'N/A'}
`;

  const token = process.env.GITHUB_TOKEN;
  const owner = process.env.GITHUB_OWNER;
  const repo = process.env.GITHUB_REPO;

  if (token && owner && repo && token !== 'your_github_token') {
    try {
      const response = await fetch(`https://api.github.com/repos/${owner}/${repo}/issues`, {
        method: 'POST',
        headers: {
          'Authorization': `token ${token}`,
          'Accept': 'application/vnd.github.v3+json',
          'User-Agent': 'ARIA-Solution-Architect-Pipeline',
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          title: issueTitle,
          body: issueBody
        })
      });

      if (!response.ok) {
        throw new Error(`GitHub API returned status ${response.status}`);
      }

      const data = await response.json();
      const integration: Integration = {
        id: 'git_' + Math.random().toString(36).substr(2, 9),
        proposalId,
        type: 'github',
        referenceUrl: data.html_url,
        referenceId: `#${data.number}`,
        status: 'Synced',
        createdAt: new Date().toISOString()
      };

      saveIntegration(proposalId, integration);
      addAuditLog(proposalId, stepName, 'GitHub Sync Completed', `Successfully published issue ${data.html_url} to GitHub.`);
      return integration;
    } catch (err) {
      console.error('Failed to create real GitHub issue, falling back to Local Sync:', err);
      addAuditLog(proposalId, stepName, 'API Error / Sync Deferred', 'GitHub service unavailable. Simulated task generated locally.');
    }
  } else {
    addAuditLog(proposalId, stepName, 'Sync Config Deferred', 'No GitHub credentials supplied. Simulated task compiled locally.');
  }

  // Fallback / Simulated local issue (Ready to Sync)
  const localIntegration: Integration = {
    id: 'git_sim_' + Math.random().toString(36).substr(2, 9),
    proposalId,
    type: 'github',
    referenceUrl: '#',
    referenceId: 'LOCAL_TASK_' + Math.floor(1000 + Math.random() * 9000),
    status: 'Ready to Sync',
    createdAt: new Date().toISOString()
  };

  saveIntegration(proposalId, localIntegration);
  addAuditLog(proposalId, stepName, 'Task Persisted Locally', 'Simulated delivery task successfully stored and flagged as "Ready to Sync".');
  return localIntegration;
}
